Using port 5684 for debugpy
Spawned debugpy process with PID: 23089
--> Sending message (seq=1):
Header: Content-Length: 321


Payload: {"seq":1,"type":"Request","command":"initialize","request_seq":null,"success":null,"body":{"adapterID":"python","clientID":"dap_test_client","clientName":"DAP Test","columnsStartAt1":true,"linesStartAt1":true,"pathFormat":"path","supportsEvaluateForHovers":true,"supportsVariableType":true},"event":null,"arguments":null}
Connecting to 127.0.0.1:5684
<-- Received: {"seq": 1, "type": "event", "event": "output", "body": {"category": "telemetry", "output": "ptvsd", "data": {"packageVersion": "1.8.12"}}}
<-- Received: {"seq": 2, "type": "event", "event": "output", "body": {"category": "telemetry", "output": "debugpy", "data": {"packageVersion": "1.8.12"}}}
--> Sending message (seq=2):
Header: Content-Length: 149


Payload: {"seq":2,"type":"Request","command":"attach","request_seq":null,"success":null,"body":null,"event":null,"arguments":{"host":"127.0.0.1","port":5684}}
Debug session launched successfully
--> Sending message (seq=3):
Header: Content-Length: 132


Payload: {"seq":3,"type":"Request","command":"configurationDone","request_seq":null,"success":null,"body":null,"event":null,"arguments":null}